# Generated by Django 5.0.6 on 2024-07-23 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dp_algos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
    ]
