# Generated by Django 5.0.6 on 2024-07-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp_algos', '0002_alter_city_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Channel Master',
                'verbose_name_plural': 'Channel Masters',
            },
        ),
    ]
