# Generated by Django 5.0.6 on 2024-07-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp_algos', '0003_channelmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Designation Master',
                'verbose_name_plural': 'Designation Masters',
            },
        ),
        migrations.CreateModel(
            name='ExecutiveMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Executive Master',
                'verbose_name_plural': 'Executive Masters',
            },
        ),
        migrations.CreateModel(
            name='ProfessionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Profession Master',
                'verbose_name_plural': 'Profession Masters',
            },
        ),
    ]
