# Generated by Django 5.0.6 on 2024-07-23 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp_algos', '0004_designationmaster_executivemaster_professionmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewMemberEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_card_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('paper_meg_channel', models.CharField(max_length=150)),
                ('valid_upto', models.DateField(auto_now=True)),
                ('father_name', models.CharField(max_length=150)),
                ('phone_no', models.CharField(max_length=13)),
                ('mobile_no', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('residence', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('pin', models.IntegerField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('qualification', models.CharField(max_length=50)),
                ('remark', models.TextField()),
                ('nature', models.CharField(choices=[('Poor', 'Poor'), ('Very Bad', 'Very Bad'), ('Medium', 'Medium'), ('Good', 'Good'), ('Excellent', 'Excellent')], max_length=15)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dp_algos.city')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dp_algos.designationmaster')),
                ('executive_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_name', to='dp_algos.executivemaster')),
                ('introducer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='introducer_name', to='dp_algos.executivemaster')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dp_algos.professionmaster')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dp_algos.state')),
            ],
            options={
                'verbose_name': 'New Member Entry',
                'verbose_name_plural': 'New Member Entries',
            },
        ),
    ]
