# Generated by Django 5.0.6 on 2024-07-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp_algos', '0005_newmemberentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmemberentry',
            name='nature',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Medium', 'Medium'), ('Good', 'Good'), ('Very Bad', 'Very Bad'), ('Poor', 'Poor')], max_length=15),
        ),
    ]
